[project]
name = "encrypted-data-vault"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "cryptography>=45.0.5",
    "streamlit>=1.47.0",
]
